### ISSUE TITLE
Global regexp variables kill parallel performance.

### ISSUE THREAD

**Issue by jrallison** [mailproto/textplain#2]
Golang's regexp implementation has a mutex for each instance of Regexp (https://golang.org/src/regexp/regexp.go). This allows concurrent method calls from different goroutines to be safe. However, during high contention, this causes performance to suffer.

https://github.com/golang/go/issues/8232

A `Copy` method was added in 2015 to work around this issue: https://go-review.googlesource.com/c/go/+/16110

We should at least remove all global regexp variables and add a way to instantiate a new instance of them, so that users of this package can create a set per goroutine.

Investigating ways to not need to regex 50+ times per conversion to plaintext would be great as well :)

**Comment by hownowstephen** [comment]
Switched to an initializer structure (https://github.com/mailproto/textplain/commit/496feff390b3f787fa9fa27fdf1546d1a5169c7c) initially. Have broken out some other planned changes into separate issues as well
